### ISSUE TITLE
ruby_gen fails with Python Exception at generation of license

### ISSUE THREAD

**Issue by orascheg** [priv-kweihmann/meta-rubygems#554]
**Describe the bug**
When generating a Yocto recipe for gems like stringio, minitest the ruby_gen tool fails with a Python exception:
Pick 3.0.8 for stringio
Traceback (most recent call last):
  File "./ruby-gen", line 391, in <module>
    main()
  File "./ruby-gen", line 387, in main
    create_tpl(args, args.gemname, args.gemversion, errata)
  File "./ruby-gen", line 358, in create_tpl
    create_tpl(args, item["name"], version, errata)
  File "./ruby-gen", line 358, in create_tpl
    create_tpl(args, item["name"], version, errata)
  File "./ruby-gen", line 358, in create_tpl
    create_tpl(args, item["name"], version, errata)
  [Previous line repeated 1 more time]
  File "./ruby-gen", line 324, in create_tpl
    __calculated["__md5sum"], __calculated["__sha256sum"], __calculated["__licfile"], __calculated["__lichash"] = get_hashes(
  File "./ruby-gen", line 201, in get_hashes
    _lic_path, _lic_hash = get_license_info(tar, _tempfolder, [r".*gemspec"])
  File "/home/ubuntu/projects/cybersecurity/meta-ruby-gems/scripts/license_util.py", line 87, in get_license_info
    _lic_path, _lic_hash = __get_from_scancode(tarball, temp_folder, excludes)
  File "/home/ubuntu/projects/cybersecurity/meta-ruby-gems/scripts/license_util.py", line 55, in __get_from_scancode
    for license in f["licenses"]:
KeyError: 'licenses'

**Used layer**
First tried with Dunfell and then with master

- hash of meta-rubygems layer
- poky hash
- hashes of additional layer

**Additional**
Add console printouts if applicable.

A fix can be done by adding a check if licenses is in the dictonary (license_util.py line 54)

    if os.path.exists(os.path.join(temp_folder.name, "scancode.res.json")):
        with open(os.path.join(temp_folder.name, "scancode.res.json")) as i:
            j = json.load(i)
            print('DEBUG j: ',j)
            for f in j["files"]:
                if any([re.match(x, f["path"]) for x in excludes]):
                    continue
                if "licenses" in f:
                  for license in f["licenses"]:
                    print("DEBUG!: License:", license)
                    if f["path"] not in res:
                        res[f["path"]] = {"start": 99999999999, "end": -1}
                    res[f["path"]]["start"] = min(
                        res[f["path"]]["start"], license["start_line"])
                    res[f["path"]]["end"] = max(res[f["path"]]["end"], license["end_line"])

**Comment by priv-kweihmann** [comment]
What version of scancode-toolkit is installed?

**Comment by orascheg** [comment]
Thanks for providing this software and the swift answer. The version of the toolkit is:

scancode-toolkit  32.0.6

If you accept the solution I can do a pull request.

**Comment by priv-kweihmann** [comment]
as set here https://github.com/priv-kweihmann/meta-rubygems/blob/3207ec3eb166f02c708671b19e4505f93f991752/scripts/requirements-package-bot.txt#L4 currently only scancode-toolkit 31.x is supported.
The data model in 32.x changed heavily and I would only accept PRs that work with both versions.

Ignoring the field, as suggested, is not an option.

Please stick to the suggested versions for the development tooling, or provide a PR that works with scancode 30.x, 31.x and 32.x in a similar way.

For now the scripts works as expected if the development guide is followed, so I don't consider this a bug
