### ISSUE TITLE
Out of intended usage, help needed

### ISSUE THREAD

**Issue by orascheg** [priv-kweihmann/meta-rubygems#597]
I thank this community for supporting ruby gems on Yocto! I know that my request is out of what you normally support, thus I'd not like this to be a bug report.
I have the challenge to support metasploit framework on a quite old Yocto (Gatesgarth). Some gems need a newer ruby, therefore I have backported ruby 3.2.2 from the actual master-next of poky. The recipies I take from meta-rubygems. Most of the stuff worked, however at rubygems-eventmachine-1.2.7 the build fails at do_populate_sysroot:
ERROR: rubygems-eventmachine-1.2.7-r0 do_populate_sysroot: Fatal errors occurred in subprocesses:
Command '['aarch64-poky-linux-strip', '--remove-section=.comment', '--remove-section=.note', '--strip-unneeded', '/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-strip: Unable to recognise the format of the input file `/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so'
Command '['aarch64-poky-linux-strip', '--remove-section=.comment', '--remove-section=.note', '--strip-unneeded', '/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/fastfilereaderext.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-strip: Unable to recognise the format of the input file `/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/fastfilereaderext.so'
Command '['aarch64-poky-linux-strip', '--remove-section=.comment', '--remove-section=.note', '--strip-unneeded', '/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/fastfilereaderext.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-strip: Unable to recognise the format of the input file `/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/fastfilereaderext.so'
Command '['aarch64-poky-linux-strip', '--remove-section=.comment', '--remove-section=.note', '--strip-unneeded', '/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/rubyeventmachine.so']' returned non-zero exit status 1.
Subprocess output:aarch64-poky-linux-strip: Unable to recognise the format of the input file `/myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/sysroot-destdir/usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/rubyeventmachine.so'

ERROR: Logfile of failure stored in: /myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/temp/log.do_populate_sysroot.30820
ERROR: Task (/myproject//meta-ruby-gems/recipes-rubygems/rubygems-eventmachine_1.2.7.bb:do_populate_sysroot) failed with exit code '1'

I have tried to make bitbake to ignore all the strip etc. checks and then it comes that some shared libraries have another architecture (x64 instead the aarch64 destination):

ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: Architecture did not match (x86-64, expected AArch64) in /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/fastfilereaderext.so
Architecture did not match (x86-64, expected AArch64) in /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so
Architecture did not match (x86-64, expected AArch64) in /usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/fastfilereaderext.so
Architecture did not match (x86-64, expected AArch64) in /usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux-gnu/3.2.0/eventmachine-1.2.7/rubyeventmachine.so [arch]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.4)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.14)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.2.5)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2 shared.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libpthread.so.0(GLIBC_2.2.5)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.3.4)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.10)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA Issue: /usr/lib64/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so contained in package rubygems-eventmachine requires libc.so.6(GLIBC_2.3.2)(64bit), but no providers found in RDEPENDS_rubygems-eventmachine? [file-rdeps]
ERROR: rubygems-eventmachine-1.2.7-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /myproject//build/tmp/work/aarch64-poky-linux/rubygems-eventmachine/1.2.7-r0/temp/log.do_package_qa.27382
ERROR: Task (/myproject//meta-cybersecurity/recipes-rubygems/rubygems-em-http-request/rubygems-eventmachine_1.2.7.bb:do_package_qa) failed with exit code '1'

Does anybody have an idea to solve that? (upgrading the poky is unfortunately not the way to go, because of BSP and a lot of other dependencies). I have taken the latest eventmachine recipe.

Thanks in advance for any proposal.

**Comment by priv-kweihmann** [comment]
Community :hugs: - Well I think it's mostly just me :smile: .

Regarding your problem I think the wrong compiler gets setup for your build.

Looking at https://github.com/priv-kweihmann/meta-rubygems/blob/9a3881d2e4a4b69ffbc8b127687adaa9fe6fad4f/classes/rubygems.bbclass#L123
 - assuming that you're using the master branch of the layer (gatesgarth of meta-rubygems is definitely way out of support) - you could do a
 
 ```shell
 bitbake rubygems-eventmachine -vv -c do_arch_patch_config -f
 ```
 
 and look for `Replace {} by {}`  pattern in the output.
 `target_cpu` needs to be something like `aarch` or `aarch64` to work.
 
 If that is not the case the setup failed entirely or some settings are wrong in your bitbake setup.
 For me it's a guessing game, as I don't know for what machine and what layer setup you configured your build.
 
 Just be assured that for `qemuarm64` everything works as expected, maybe that's worth a try for you as well to rule out MACHINE or BSP specific issues

**Comment by orascheg** [comment]
Thanks for the hint. I tried the bitbake and it runs through with a warning:

WARNING: /myproject/meta-ruby-gems/recipes-rubygems/rubygems-eventmachine_1.2.7.bb:do_arch_patch_config is tainted from a forced run 0:00:00

I do not really understand what this means. What pattern shall I look for?

**Comment by priv-kweihmann** [comment]
You didn't answer the question if 'target_cpu' is set correctly, so I think there is still something wrong on your end.

Again, please try building with meta-rubygems:master or any of the best matching branches for your poly release using qemuarm64.

If something goes south with that, I happily assist, but if not it might be mainly an issue with the Bsp you use or this frankenbuild with the backported ruby.

For the latter, I could only offer to take a look into it as part of paid work.

**Comment by orascheg** [comment]
bitbake rubygems-eventmachine -e delivers a lot of output. I have search for TARGET_ARCH, this is what I have found (beside many others):
HOST_ARCH="aarch64"
# $PREFERRED_PROVIDER_virtual/aarch64-poky-linux-binutils [2 operations]
#   set /myproject/poky/meta/conf/distro/include/tcmode-default.inc:5
#     "binutils-cross-${TARGET_ARCH}"
#   rename from PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}binutils data.py:104 [expandKeys]
#     "binutils-cross-${TARGET_ARCH}"
# pre-expansion value:
#   "binutils-cross-${TARGET_ARCH}"
PREFERRED_PROVIDER_virtual/aarch64-poky-linux-binutils="binutils-cross-aarch64"

In the build directory rubygems-eventmachine is stored in aarch64-poky-linux, thus I do think that the target architecture is set. How can I check 'target_cpu'? Sorry, I am not very experienced in Yocto yet (therefore I do not dare to try to maintain the Dunfell/Gatesgarth part of this project ;-)

I will try to build for qemuarm64 (do not know how to do that yet - the solution uses Kas above bitbake). I have built against master branch and have fallen into another trap, where I do not know how it is connected (docker-ce does not build anymore...). Will update when I have new findings.

**Comment by orascheg** [comment]
The recipe builds now, thanks for your support. We can close the issue. I continue my work on rubygems-pcaprub which makes problems with mixing local machine and recipe includes. (The install log indicates that host include and/or library paths were used.) If I succeed and somebody has usage for that gem, please tell.

**Comment by priv-kweihmann** [comment]
> pcaprub

That seems to be an issue with the code itself https://github.com/pcaprub/pcaprub/blob/master/ext/pcaprub_c/extconf.rb - there is no option to enforce a path to the lib/include dirs, so if you have (lib)pcap installed on your build host, that one might get chosen over the one from the build root.
What you could do is to remove all the other options from `header_dirs` and `lib_dirs` and just leave `libdir` resp. `installdir` there.

Good luck making it work - sadly some ruby gems are just a mess when it comes to cross compiling
