### ISSUE TITLE
Package request: sqlite3

### ISSUE THREAD

**Issue by dive-gozo** [priv-kweihmann/meta-rubygems#609]
**sqlite3**

Ruby library to interface with the SQLite3 database engine (http://www.sqlite.org).

**Link to gem on rubygems.org**

https://rubygems.org/gems/sqlite3

**Comment by dive-gozo** [comment]
I'd like to open a pull-request for the rubygems-sqlite3_1.7.2.bb recipe (created with ruby-gen), tested on my i.MX6UL platform with SQLite3 3.38.5 and Ruby 3.1.4.

**Comment by priv-kweihmann** [comment]
Sure, PRs are welcome - please see https://github.com/priv-kweihmann/meta-rubygems/blob/master/scripts/README.md for the dev/contribution guide for this repo.
Please mind that PRs need to be raised against master branch (currently ruby 3.2.x) and need to pass CI for qemu-aarch64

**Comment by dive-gozo** [comment]
Successfully tested on master running `MACHINE=qemuarm64 bitbake core-image-minimal-rubygems -c testimage`. Additionally, I did a smoke test with some SQL statements.
Would you like to give me access to the repo, such that I can push my feature branch for the PR?

**Comment by priv-kweihmann** [comment]
@dive-gozo suggested workflow is: fork it and raise a PR against master branch.
The rest will be handled by CI.

Direct repo access only for maintainers

**Comment by priv-kweihmann** [comment]
Merged your PR, thanks for the contribution

**Comment by dive-gozo** [comment]
Thank you for your guidance and accepting my PR 😃
